# Generated by Django 3.0.4 on 2020-03-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_published',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
